const imagenesProductos = document.querySelectorAll("imagen-carta")

const productos = [{
    codigo: 100,
    nombre: 'Encendedor catalítico',
    imagen: imagenesProductos.src = "../img/productos/precio1.jpg",
    precio: 5000,
    cantidad: 1,
},
{
    codigo: 101,
    nombre: 'Picador Burguer',
    imagen: imagenesProductos.src = "../img/productos/precio2.jpg",
    precio: 12000,
    cantidad: 1,
},
{
    codigo: 102,
    nombre: 'Armador auto tabaco',
    imagen: imagenesProductos.src = "../img/productos/precio3.jpg",
    precio: 10000,
    cantidad: 1,
},
{
    codigo: 103,
    nombre: 'Bandeja vidrio mini',
    imagen: imagenesProductos.src = "../img/productos/precio4.jpg",
    precio: 10000,
    cantidad: 1,
},
{
    codigo: 104,
    nombre: 'Miracle',
    imagen: imagenesProductos.src = "../img/productos/precio5.jpg",
    precio: 5000,
    cantidad: 1,
},
{
    codigo: 105,
    nombre: 'Papelillo elements 1/4',
    imagen: imagenesProductos.src = "../img/productos/precio6.jpg",
    precio: 500,
    cantidad: 1,
},
{
    codigo: 106,
    nombre: 'Cajita papelillo',
    imagen: imagenesProductos.src = "../img/productos/precio7.jpg",
    precio: 7000,
    cantidad: 1,
},
{
    codigo: 107,
    nombre: 'Picador 2P acrílico',
    imagen: imagenesProductos.src = "../img/productos/precio8.jpg",
    precio: 1500,
    cantidad: 1,
},
{
    codigo: 108,
    nombre: 'Tabaco sayri 50gr',
    imagen: imagenesProductos.src = "../img/productos/precio9.jpg",
    precio: 3000,
    cantidad: 1,
},
{
    codigo: 109,
    nombre: 'Clippers (c/u)',
    imagen: imagenesProductos.src = "../img/productos/precio10.jpg",
    precio: 1000,
    cantidad: 1,
},
{
    codigo: 110,
    nombre: 'Pica llaveros mini',
    imagen: imagenesProductos.src = "../img/productos/precio11.jpg",
    precio: 4000,
    cantidad: 1,
},
{
    codigo: 111,
    nombre: 'Cenicero de resina',
    imagen: imagenesProductos.src = "../img/productos/precio12.jpg",
    precio: 7500,
    cantidad: 1,
}
]